version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: caisse
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  caisse1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CAISSE_ID: 1
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: caisse
      DB_USER: posuser
      DB_PASS: pospass
    depends_on:
      - db
  caisse2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CAISSE_ID: 2
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: caisse
      DB_USER: posuser
      DB_PASS: pospass
    depends_on:
      - db
  caisse3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CAISSE_ID: 3
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: caisse
      DB_USER: posuser
      DB_PASS: pospass
    depends_on:
      - db

volumes:
  db_data:
